"""Phase input and output schemas for the pipeline."""

from __future__ import annotations

from pydantic import Field

from rentl_schemas.base import BaseSchema
from rentl_schemas.io import SourceLine, TranslatedLine
from rentl_schemas.primitives import (
    AnnotationId,
    AnnotationType,
    JsonValue,
    LanguageCode,
    LineId,
    NoteId,
    PhaseName,
    RunId,
    SceneId,
)
from rentl_schemas.qa import LineEdit, QaIssue, QaSummary, ReviewerNote


class SceneSummary(BaseSchema):
    """Summary for a scene generated during context phase."""

    scene_id: SceneId = Field(..., description="Scene identifier")
    summary: str = Field(..., min_length=1, description="Scene summary")
    characters: list[str] = Field(..., description="Relevant characters")


class ContextNote(BaseSchema):
    """Context note associated with a line or scene."""

    note_id: NoteId = Field(..., description="Context note id")
    line_id: LineId | None = Field(None, description="Associated line identifier")
    scene_id: SceneId | None = Field(None, description="Associated scene identifier")
    note: str = Field(..., min_length=1, description="Context note")


class GlossaryTerm(BaseSchema):
    """Glossary term for translation guidance."""

    term: str = Field(..., min_length=1, description="Source term")
    translation: str = Field(..., min_length=1, description="Preferred translation")
    notes: str | None = Field(None, description="Optional glossary notes")


class PretranslationAnnotation(BaseSchema):
    """Line-level annotation produced during pretranslation."""

    annotation_id: AnnotationId = Field(..., description="Annotation identifier")
    line_id: LineId = Field(..., description="Line identifier for the annotation")
    annotation_type: AnnotationType = Field(..., description="Annotation type")
    value: str | None = Field(None, description="Annotation value if applicable")
    notes: str | None = Field(None, description="Annotation notes")
    metadata: dict[str, JsonValue] | None = Field(
        None, description="Structured annotation metadata"
    )


class TermCandidate(BaseSchema):
    """Terminology candidate extracted from pretranslation."""

    term: str = Field(..., min_length=1, description="Source term")
    notes: str | None = Field(None, description="Terminology notes")
    preferred_translation: str | None = Field(
        None, description="Preferred translation if known"
    )


class ContextPhaseInput(BaseSchema):
    """Input payload for the context phase."""

    run_id: RunId = Field(..., description="Run identifier")
    source_lines: list[SourceLine] = Field(
        ..., min_length=1, description="Source lines"
    )
    project_context: str | None = Field(None, description="High-level project context")
    style_guide: str | None = Field(None, description="Style guide content")
    glossary: list[GlossaryTerm] | None = Field(None, description="Glossary terms")


class ContextPhaseOutput(BaseSchema):
    """Output payload for the context phase."""

    run_id: RunId = Field(..., description="Run identifier")
    phase: PhaseName = Field(PhaseName.CONTEXT, description="Phase name")
    project_context: str | None = Field(
        None, description="Project context generated by the phase"
    )
    style_guide: str | None = Field(
        None, description="Style guide generated by the phase"
    )
    glossary: list[GlossaryTerm] | None = Field(
        None, description="Glossary generated by the phase"
    )
    scene_summaries: list[SceneSummary] = Field(..., description="Scene summaries")
    context_notes: list[ContextNote] = Field(..., description="Context notes")


class PretranslationPhaseInput(BaseSchema):
    """Input payload for the pretranslation phase."""

    run_id: RunId = Field(..., description="Run identifier")
    source_lines: list[SourceLine] = Field(
        ..., min_length=1, description="Source lines"
    )
    scene_summaries: list[SceneSummary] | None = Field(
        None, description="Context scene summaries"
    )
    context_notes: list[ContextNote] | None = Field(None, description="Context notes")
    project_context: str | None = Field(None, description="Project context")
    glossary: list[GlossaryTerm] | None = Field(None, description="Glossary terms")


class PretranslationPhaseOutput(BaseSchema):
    """Output payload for the pretranslation phase."""

    run_id: RunId = Field(..., description="Run identifier")
    phase: PhaseName = Field(PhaseName.PRETRANSLATION, description="Phase name")
    annotations: list[PretranslationAnnotation] = Field(
        ..., description="Pretranslation annotations"
    )
    term_candidates: list[TermCandidate] = Field(
        ..., description="Terminology candidates"
    )


class TranslatePhaseInput(BaseSchema):
    """Input payload for the translate phase."""

    run_id: RunId = Field(..., description="Run identifier")
    target_language: LanguageCode = Field(..., description="Target language code")
    source_lines: list[SourceLine] = Field(
        ..., min_length=1, description="Source lines"
    )
    scene_summaries: list[SceneSummary] | None = Field(
        None, description="Context scene summaries"
    )
    context_notes: list[ContextNote] | None = Field(None, description="Context notes")
    project_context: str | None = Field(None, description="Project context")
    pretranslation_annotations: list[PretranslationAnnotation] | None = Field(
        None, description="Pretranslation annotations"
    )
    term_candidates: list[TermCandidate] | None = Field(
        None, description="Terminology candidates"
    )
    glossary: list[GlossaryTerm] | None = Field(None, description="Glossary terms")
    style_guide: str | None = Field(None, description="Style guide content")


class TranslatePhaseOutput(BaseSchema):
    """Output payload for the translate phase."""

    run_id: RunId = Field(..., description="Run identifier")
    phase: PhaseName = Field(PhaseName.TRANSLATE, description="Phase name")
    target_language: LanguageCode = Field(..., description="Target language code")
    translated_lines: list[TranslatedLine] = Field(
        ..., min_length=1, description="Translated lines"
    )


class QaPhaseInput(BaseSchema):
    """Input payload for the QA phase."""

    run_id: RunId = Field(..., description="Run identifier")
    target_language: LanguageCode = Field(..., description="Target language code")
    source_lines: list[SourceLine] = Field(
        ..., min_length=1, description="Source lines"
    )
    translated_lines: list[TranslatedLine] = Field(
        ..., min_length=1, description="Translated lines"
    )
    scene_summaries: list[SceneSummary] | None = Field(
        None, description="Context scene summaries"
    )
    context_notes: list[ContextNote] | None = Field(None, description="Context notes")
    project_context: str | None = Field(None, description="Project context")
    glossary: list[GlossaryTerm] | None = Field(None, description="Glossary terms")
    style_guide: str | None = Field(None, description="Style guide content")


class QaPhaseOutput(BaseSchema):
    """Output payload for the QA phase."""

    run_id: RunId = Field(..., description="Run identifier")
    phase: PhaseName = Field(PhaseName.QA, description="Phase name")
    target_language: LanguageCode = Field(..., description="Target language code")
    issues: list[QaIssue] = Field(..., description="QA issues")
    summary: QaSummary = Field(..., description="QA summary")


class EditPhaseInput(BaseSchema):
    """Input payload for the edit phase."""

    run_id: RunId = Field(..., description="Run identifier")
    target_language: LanguageCode = Field(..., description="Target language code")
    translated_lines: list[TranslatedLine] = Field(
        ..., min_length=1, description="Translated lines"
    )
    qa_issues: list[QaIssue] | None = Field(None, description="QA issues to address")
    reviewer_notes: list[ReviewerNote] | None = Field(
        None, description="Reviewer notes"
    )
    scene_summaries: list[SceneSummary] | None = Field(
        None, description="Context scene summaries"
    )
    context_notes: list[ContextNote] | None = Field(None, description="Context notes")
    project_context: str | None = Field(None, description="Project context")
    pretranslation_annotations: list[PretranslationAnnotation] | None = Field(
        None, description="Pretranslation annotations"
    )
    term_candidates: list[TermCandidate] | None = Field(
        None, description="Terminology candidates"
    )
    glossary: list[GlossaryTerm] | None = Field(None, description="Glossary terms")
    style_guide: str | None = Field(None, description="Style guide content")


class EditPhaseOutput(BaseSchema):
    """Output payload for the edit phase."""

    run_id: RunId = Field(..., description="Run identifier")
    phase: PhaseName = Field(PhaseName.EDIT, description="Phase name")
    target_language: LanguageCode = Field(..., description="Target language code")
    edited_lines: list[TranslatedLine] = Field(
        ..., min_length=1, description="Edited lines"
    )
    change_log: list[LineEdit] = Field(..., description="Line edit records")
